In [1]:
 import numpy as np
 np.random.seed(0) # 设置随机数种子

In [3]:
x1 = np.random.randint(10, size=6) # 一维数组
x2 = np.random.randint(10, size=(3, 4)) # 二维数组
x3 = np.random.randint(10, size=(3, 4, 5)) # 三维数组

In [4]:
x1

array([5, 0, 3, 3, 7, 9])

In [5]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [6]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [7]:
 print("x3 ndim: ", x3.ndim)
 print("x3 shape:", x3.shape)
 print("x3 size: ", x3.size) 

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [8]:
print("x3 dtype: ", x3.dtype)

x3 dtype:  int32


In [9]:
 print("itemsize:", x3.itemsize, "bytes")
 print("nbytes:", x3.nbytes, "bytes") 

itemsize: 4 bytes
nbytes: 240 bytes


请注意，和 Python 列表不同，NumPy 数组是固定类型的。这意味着当你试图将一个浮点
值插入一个整型数组时，浮点值会被截短成整型。并且这种截短是自动完成的，不会给你
提示或警告，所以需要特别注意这一点！

In [12]:
x = np.arange(10)

In [13]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
x[::2]

array([0, 2, 4, 6, 8])

In [15]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [16]:
x[5::-1]

array([5, 4, 3, 2, 1, 0])

In [17]:
x[5::-2]

array([5, 3, 1])

In [20]:
x2 =  np.array([[12, 5, 2, 4],
 [ 7, 6, 8, 8],
 [ 1, 6, 7, 7]])

In [21]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [22]:
x2[:2, :3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [23]:
x2[:, ::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [24]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [25]:
x2_sub_copy = x2[:2, :2].copy()

In [26]:
 grid = np.arange(1, 10).reshape((3, 3))
 print(grid) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [32]:
x = np.array([1, 2, 3])

In [33]:
x

array([1, 2, 3])

In [34]:
x.reshape(1, 3)

array([[1, 2, 3]])

In [35]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [36]:
 x = np.array([1, 2, 3])
 y = np.array([3, 2, 1])
 np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [37]:
grid = np.array([[1, 2, 3],
 [4, 5, 6]])

In [38]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [39]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [40]:
 x = np.array([1, 2, 3])
 grid = np.array([[9, 8, 7],
 [6, 5, 4]])

In [41]:
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [42]:
y = np.array([[99],
 [99]])

In [43]:
y

array([[99],
       [99]])

In [44]:
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [45]:
 x = [1, 2, 3, 99, 99, 3, 2, 1]
 x1, x2, x3 = np.split(x, [3, 5])

In [46]:
x1

array([1, 2, 3])

In [47]:
x2

array([99, 99])

In [48]:
x3

array([3, 2, 1])