In [9]:
# 通用函数就是 ufunc
import numpy as np
np.random.seed(0)

In [10]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

In [12]:
values = np.random.randint(1, 10, size = 5)
compute_reciprocals(values)

array([0.25      , 0.16666667, 0.33333333, 0.2       , 0.125     ])

In [16]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [17]:
b = np.arange(1, 6)
b

array([1, 2, 3, 4, 5])

In [18]:
a / b

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

通过通用函数用向量的方式进行计算几乎总比用 Python 循环实现的计算更加有效，尤其是
当数组很大时。只要你看到 Python 脚本中有这样的循环，就应该考虑能否用向量方式替换
这个循环。

In [19]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [20]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [21]:
x = np.arange(1, 6)
np.add.reduce(x)

15

In [22]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [23]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])