In [3]:
import numpy as np

In [4]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [5]:
 np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [6]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [13]:
np.ones([2, 3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.full((2, 3), 3.14)

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [18]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
np.random.random((3,3))

array([[0.60446591, 0.72565355, 0.34922934],
       [0.87127339, 0.96318873, 0.27978644],
       [0.09697342, 0.61988833, 0.02986526]])

In [22]:
np.random.normal(0, 1, (3, 3))

array([[ 1.60488412,  0.59929604, -2.45088586],
       [ 0.60977421, -0.03404215, -0.16244227],
       [-1.64678423, -0.60472164,  0.41280506]])

In [23]:
np.random.randint(0, 10, (3, 3))

array([[1, 9, 6],
       [0, 6, 5],
       [5, 7, 0]])

In [24]:
np.empty(3)

array([0.0078125, 0.0078125, 0.0078125])

In [26]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [27]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower) 

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [28]:
left, right = np.hsplit(grid, [2])

In [29]:
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
